import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import SideFrames from "@/components/ui/SideFrames";
import {
  fontKhula,
  fontLibre_BaskervilleItalic,
  fontNoto_Sans_Display,
  fontRakkas,
  fontPacifico,
} from "@/lib/utils/fonts";
import Navigation from "@/components/layout/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${fontKhula.variable} ${fontLibre_BaskervilleItalic.variable}
        ${fontNoto_Sans_Display.variable} ${fontRakkas.variable} ${fontPacifico.variable}`}
        suppressHydrationWarning
      >
        <Navigation />
        {children}
      </body>
    </html>
  );
}
