version: '3.8'
services:
  traefik:
    container_name: portfolio-v3-traefik
    image: traefik:v3.3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../../infrastructure/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ../../../infrastructure/traefik/config:/etc/traefik/config:ro
      - traefik-certificates:/letsencrypt
    networks:
      - app-network
    restart: always

  mongodb:
    container_name: portfolio-v3-mongo-prod
    build:
      context: ../../..
      dockerfile: ./infrastructure/docker/production/mongodb.Dockerfile
    volumes:
      - mongodb_data:/data/db
      - ../mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
    env_file:
      - ../../../backend/.env.production
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: always
    networks:
      - app-network

  backend:
    container_name: portfolio-v3-backend-prod
    build: 
      context: ../../..
      dockerfile: ./infrastructure/docker/production/backend.Dockerfile
    env_file:
      - ../../../backend/.env.production
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=(Host(`elomar.be`) || Host(`www.elomar.be`)) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend.loadbalancer.server.port=5000"
      - "traefik.http.middlewares.compress.compress=compress@file"
  
  frontend:
    container_name: portfolio-v3-frontend-prod
    build:
      context: ../../..
      dockerfile: ./infrastructure/docker/production/frontend.Dockerfile
    env_file:
      - ../../../frontend/.env.production
    depends_on:
      - backend
    restart: always
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`elomar.be`) || Host(`www.elomar.be`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.routers.frontend.middlewares=compress@file"

volumes:
  mongodb_data:
  traefik-certificates:

networks:
  app-network:
    driver: bridge 