version: '3.8'
services:
  mongodb:
    container_name: portfolio-v3-mongo
    image: mongo:latest
    ports:
      - "27017:27017"
    command: mongod --bind_ip_all
    volumes:
      - mongodb_data:/data/db
      - ./config/mongodb/init.js:/docker-entrypoint-initdb.d/init.js:ro
    env_file:
      - ../../backend/.env.development
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - app-network

  shared:
    container_name: portfolio-v3-shared
    build:
      context: ../..
      dockerfile: ./infrastructure/docker/shared.Dockerfile
    command: yarn workspace @portfolio-v3/shared watch
    volumes:
      - ../../shared:/usr/src/app/shared

  backend:
    container_name: portfolio-v3-backend
    build: 
      context: ../..
      dockerfile: ./infrastructure/docker/backend.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../../backend:/usr/src/app/backend
      - ../../shared:/usr/src/app/shared
    env_file:
      - ../../backend/.env.development
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
  
  frontend:
    container_name: portfolio-v3-frontend
    build:
      context: ../..
      dockerfile: ./infrastructure/docker/frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../../frontend:/usr/src/app/frontend
      - ../../shared:/usr/src/app/shared
    env_file:
      - ../../frontend/.env.development
    depends_on:
      - backend
    command: yarn workspace frontend dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: